# Generated by Django 4.1.4 on 2023-02-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu', models.TextField(verbose_name='luri')),
                ('pe', models.TextField(verbose_name='parsi')),
                ('result', models.IntegerField(choices=[(1, 'khaas'), (2, 'minjaa'), (3, 'ga`n')], default=1, verbose_name='natije')),
                ('sound', models.FileField(blank=True, null=True, upload_to='', verbose_name='dang')),
            ],
        ),
    ]
